#!/usr/bin/env php
<?php

array_shift($argv);
defined('DS') ? null : define('DS', DIRECTORY_SEPARATOR);

$task = empty($argv) ? false : array_shift($argv);
$task = !in_array($task,get_class_methods('Makelos')) ? 'help' : $task;

include(dirname(__FILE__).str_repeat(DS.'..', 4).DS.'config'.DS.'config.php');

class Makelos
{
    var $repository = 'http://svn.akelos.org/plugins/acts_as_statemachine';

    function help()
    {
        echo "\nValid commands are ".join(', ', get_class_methods('Makelos'))."\n";
    }

    function test($options = array())
    {
        system('/usr/bin/env php '.dirname(__FILE__).'/test/acts_as_statemachine.php');
    }

    function install()
    {
        $Installer =& $this->_getInstaller();
        $Installer->install();
    }

    function uninstall()
    {
        $Installer =& $this->_getInstaller();
        $Installer->uninstall();
    }

    function &_getInstaller()
    {
        require_once(dirname(__FILE__).DS.'installer'.DS.'acts_as_statemachine_installer.php');
        $Installer =& new ActsAsStatemachineInstaller();
        return $Installer;
    }

    function connectToDatabase($database_settings)
    {
        $this->_includeDependencies();
        Ak::db($database_settings[AK_ENVIRONMENT]);
    }
    
    function _includeDependencies()
    {
        require_once(AK_LIB_DIR.DS.'Ak.php');
        require_once(AK_LIB_DIR.DS.'AkObject.php');
        require_once(AK_LIB_DIR.DS.'AkInflector.php');
        require_once(AK_LIB_DIR.DS.'AkPlugin.php');
        require_once(AK_LIB_DIR.DS.'AkPlugin/AkPluginManager.php');
        require_once(AK_LIB_DIR.DS.'AkInstaller.php');
        require_once(AK_LIB_DIR.DS.'utils'.DS.'generators'.DS.'AkelosGenerator.php');
    }
}

$Makelos = new Makelos();
$Makelos->connectToDatabase($database_settings);
$Makelos->$task(@$argv);


?>
